version: "3.4"
services:
  graphql-poc:
    image: graphql-poc-api
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
